<?php
/**
 * db/generate_seed.php — regenerate db/seed.sql from content/db/*.json.
 *
 * db/seed.sql is a plain MySQL dump (no PHP execution needed to load it) —
 * for hosting without easy SSH/CLI access, import it directly through
 * phpMyAdmin (hPanel -> Databases -> phpMyAdmin -> select your database ->
 * Import -> choose db/seed.sql -> Go) instead of running `php db/migrate.php`.
 * It's an alternative destination for the same content, not a second
 * source of truth — always edit content/db/*.json, then run *both*
 * `php db/migrate.php` (if you have CLI access) and this generator (to
 * keep seed.sql matching, for whoever imports it via phpMyAdmin instead).
 *
 * Run locally (not on the server): php db/generate_seed.php
 */

if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    die('Run this from the CLI: php db/generate_seed.php');
}

function mysql_escape(string $s): string {
    return str_replace(["\\", "'"], ["\\\\", "\\'"], $s);
}

function sql_string(string $s): string {
    return "'" . mysql_escape($s) . "'";
}

$out = [];
$out[] = '-- db/seed.sql — generated by db/generate_seed.php from content/db/*.json.';
$out[] = '-- Import via phpMyAdmin (hPanel -> Databases -> phpMyAdmin -> your DB -> Import)';
$out[] = '-- as an alternative to running `php db/migrate.php` when SSH/CLI isn\'t available.';
$out[] = '-- Safe to re-import any time content/db/*.json changes and this file is regenerated.';
$out[] = '';
$out[] = 'CREATE TABLE IF NOT EXISTS languages (';
$out[] = '  code       VARCHAR(5)  NOT NULL PRIMARY KEY,';
$out[] = '  name       VARCHAR(40) NOT NULL,';
$out[] = '  is_default TINYINT(1)  NOT NULL DEFAULT 0';
$out[] = ');';
$out[] = '';
$out[] = 'CREATE TABLE IF NOT EXISTS i18n_strings (';
$out[] = '  lang_code  VARCHAR(5)   NOT NULL,';
$out[] = '  section    VARCHAR(80)  NOT NULL,';
$out[] = '  content    LONGTEXT     NOT NULL,';
$out[] = '  updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,';
$out[] = '  PRIMARY KEY (lang_code, section)';
$out[] = ');';
$out[] = '';

$languages = ['et' => 'Eesti', 'en' => 'English', 'de' => 'Deutsch', 'sv' => 'Svenska', 'nb' => 'Norsk'];
foreach ($languages as $code => $name) {
    $isDefault = $code === 'et' ? 1 : 0;
    $out[] = "INSERT INTO languages (code, name, is_default) VALUES (" . sql_string($code) . ', ' . sql_string($name) . ", {$isDefault})"
        . " ON DUPLICATE KEY UPDATE name = VALUES(name), is_default = VALUES(is_default);";
}
$out[] = '';

$contentDir = __DIR__ . '/../content/db';
$rows = 0;

$globalPath = $contentDir . '/global.json';
$byLang = json_decode(file_get_contents($globalPath), true);
foreach ($byLang as $lang => $content) {
    $json = json_encode($content, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    $out[] = "INSERT INTO i18n_strings (lang_code, section, content) VALUES (" . sql_string($lang) . ", 'global', " . sql_string($json) . ")"
        . " ON DUPLICATE KEY UPDATE content = VALUES(content);";
    $rows++;
}
$out[] = '';

foreach (glob($contentDir . '/pages/*.json') as $path) {
    $slug = basename($path, '.json');
    $byLang = json_decode(file_get_contents($path), true);
    foreach ($byLang as $lang => $content) {
        $json = json_encode($content, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        $out[] = "INSERT INTO i18n_strings (lang_code, section, content) VALUES (" . sql_string($lang) . ", " . sql_string("page:{$slug}") . ", " . sql_string($json) . ")"
            . " ON DUPLICATE KEY UPDATE content = VALUES(content);";
        $rows++;
    }
    $out[] = '';
}

file_put_contents(__DIR__ . '/seed.sql', implode("\n", $out) . "\n");
echo "Wrote db/seed.sql — {$rows} (language, section) rows.\n";
